# Generated by Django 4.0.2 on 2022-10-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
